### ISSUE TITLE
predicts = predicts['res']

### ISSUE THREAD

**Issue by Alexander-code-365** [WenmuZhou/PytorchOCR#288]
请教大佬 predicts = predicts['res'] in rec_ctc_loss and rec_sar_loss get wrong?

**Comment by Alexander-code-365** [comment]
直接注释掉，loss震荡在70左右。。

**Comment by WenmuZhou** [comment]
具体报什么错误呢

**Comment by guanfuchen** [comment]
遇到相同的问题
File "/mnt/cgf/code/PytorchOCR-dev/torchocr/losses/rec_ctc_loss.py", line 13, in forward
    predicts = predicts['res']
TypeError: new(): invalid data type 'str'

**Comment by WenmuZhou** [comment]
> 遇到相同的问题 File "/mnt/cgf/code/PytorchOCR-dev/torchocr/losses/rec_ctc_loss.py", line 13, in forward predicts = predicts['res'] TypeError: new(): invalid data type 'str'

跑的哪个配置文件

**Comment by JasonG98** [comment]
> 遇到相同的问题 File "/mnt/cgf/code/PytorchOCR-dev/torchocr/losses/rec_ctc_loss.py", line 13, in forward predicts = predicts['res'] TypeError: new(): invalid data type 'str'

同样的，我在跑 configs/rec/PP-OCRv4/ch_PP-OCRv4_rec_distill.yml 时也遇到了。目前没解决。

**Comment by Mr-lonely0** [comment]
我也一样，请问各位都解决这个问题了吗，或者是如何绕过的呢？

**Comment by WenmuZhou** [comment]
student和teacher训练有没有问题呢

**Comment by Mr-lonely0** [comment]
> student和teacher训练有没有问题呢

我将报错的这一行注释掉后跑了一下，这是log文件，请问这是正常的吗？
[20240818_rec.log](https://github.com/user-attachments/files/16658409/20240818_rec.log)

**Comment by WenmuZhou** [comment]
不正常，加载一个预训练模型试试

**Comment by WenmuZhou** [comment]
属于bug，今天已经修复

**Comment by Mr-lonely0** [comment]
我在跑v3 rec 的时候还是会遇到这个问题，报错信息如下：
``` txt
Traceback (most recent call last):
  File "tools/train.py", line 38, in <module>
    main()
  File "tools/train.py", line 34, in main
    trainer.train()
  File "/data_1/lk/PytorchOCR/torchocr/engine/trainer.py", line 181, in train
    loss = self.loss_class(preds, batch)
  File "/data_1/lk/miniconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data_1/lk/PytorchOCR/torchocr/losses/combined_loss.py", line 44, in forward
    loss = loss_func(input, batch, **kargs)
  File "/data_1/lk/miniconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data_1/lk/PytorchOCR/torchocr/losses/distillation_loss.py", line 95, in forward
    loss = super().forward(out1[self.dis_head]['res'],
TypeError: new(): invalid data type 'str'
```
配置文件是`configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml`，下面是我的config，主要修改了数据和模型路径：
``` yml
Global:
  device: gpu
  epoch_num: 400
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/rec_ppocr_v3_distillation
  eval_epoch_step: [0, 1]
  cal_metric_during_train: true
  pretrained_model: pretrained_models/ch_PP-OCRv3_rec/best_accuracy.pth
  checkpoints:
  use_tensorboard: false
  infer_mode: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: &character_dict_path torchocr/utils/ppocr_keys_v1.txt
  max_text_length: &max_text_length 25
  use_space_char: &use_space_char true

Export:
  export_dir:
  export_shape: [ 1, 3, 48, 320 ]
  dynamic_axes: [ 0, 2, 3 ]

Optimizer:
  name: Adam
  lr: 0.0005
  weight_decay: 3.0e-05
  amsgrad: true

LRScheduler:
  name: MultiStepLR
  milestones: [700]
  warmup_epoch: 5

Architecture:
  model_type: &model_type "rec"
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: SVTR_LCNet
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
        last_conv_stride: [1, 2]
        last_pool_type: avg
        last_pool_kernel_size: [2, 2]
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 64
                depth: 2
                hidden_dims: 120
                use_guide: True
          - SARHead:
              enc_dim: 512
              max_text_length: *max_text_length
    Student:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: SVTR_LCNet
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
        last_conv_stride: [1, 2]
        last_pool_type: avg
        last_pool_kernel_size: [2, 2]
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 64
                depth: 2
                hidden_dims: 120
                use_guide: True
              Head:
                fc_decay: 0.00001
          - SARHead:
              enc_dim: 512
              max_text_length: *max_text_length
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDMLLoss:
      weight: 1.0
      act: "softmax"
      use_log: true
      model_name_pairs:
      - ["Student", "Teacher"]
      key: head_out
      multi_head: True
      dis_head: ctc
      name: dml_ctc
  - DistillationDMLLoss:
      weight: 0.5
      act: "softmax"
      use_log: true
      model_name_pairs:
      - ["Student", "Teacher"]
      key: head_out
      multi_head: True
      dis_head: sar
      name: dml_sar
  - DistillationDistanceLoss:
      weight: 1.0
      mode: "l2"
      model_name_pairs:
      - ["Student", "Teacher"]
      key: backbone_out
  - DistillationCTCLoss:
      weight: 1.0
      model_name_list: ["Student", "Teacher"]
      key: head_out
      multi_head: True
  - DistillationSARLoss:
      weight: 1.0
      model_name_list: ["Student", "Teacher"]
      key: head_out
      multi_head: True

PostProcess:
  name: DistillationCTCLabelDecode
  model_name: ["Student", "Teacher"]
  key: head_out
  multi_head: True
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char


Metric:
  name: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: "Student"
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/word_recognition
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/icdar2015/word_recognition/rec_gt_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/word_recognition
    label_file_list:
    - ./train_data/icdar2015/word_recognition/rec_gt_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
```
请问该如何解决呢 : )
